CREATE (ar2:Architecture2 {name: "ARCH002", type: "Architecture2" }), (eps2:EPS2 {name: "EPS2", type: "Subsystem2" }), (aocs2:AOCS2{name: "AOCS2", type: "Subsystem2"}), (tcs2:TCS2{name: "TCS2", type: "Subsystem2"}), (strsn2:Star2{name: "Star Sensor2", type: "Component2"}), (li2:lidar2{name: "LiDAR2", type: "Component2"}), (sa2:solar2{name: "Solar Array2", type: "Component2"}), (ra2:radiator2{name: "Radiator2", type: "Component2"}), (ac2:accuracy2{name: "Accuracy2", type: "Metric2"}), (ct2:cost2{name: "Cost2", type: "Metric2"}), (ar2)-[:CONTAINS2 {since:2021}]->(eps2), (ar2)-[:CONTAINS2 {since:2021}]->(tcs2), (ar2)-[:CONTAINS2 {since:2021}]->(aocs2), (aocs2)-[:HAS2 {since:2021}]->(strsn2), (aocs2)-[:HAS2 {since:2021}]->(li2), (tcs2)-[:HAS2 {since:2021}]->(ra2), (eps2)-[:HAS2 {since:2021}]->(sa2), (li2)-[:FUNCTION_OF2 {since:2021}]->(ac2), (strsn2)-[:FUNCTION_OF2 {since:2021}]->(ac2), (li2)-[:FUNCTION_OF2 {since:2021}]->(ct2), (strsn2)-[:FUNCTION_OF2 {since:2021}]->(ct2), (sa2)-[:FUNCTION_OF2 {since:2021}]->(ct2), (ra2)-[:FUNCTION_OF2 {since:2021}]->(ct2) RETURN ar2, eps2, aocs2, tcs2, strsn2, li2, sa2, ra2, ac2, ct2

CREATE (ar:Architecture {name: "ARCH001", type: "Architecture" }), (eps:EPS {name: "EPS", type: "Subsystem" }), (aocs:AOCS{name: "AOCS", type: "Subsystem"}), (tcs:TCS{name: "TCS", type: "Subsystem"}), (strsn:Star{name: "Star Sensor", type: "Component"}), (li:lidar{name: "LiDAR", type: "Component"}), (sa:solar{name: "Solar Array", type: "Component"}), (ra:radiator{name: "Radiator", type: "Component"}), (ac:accuracy{name: "Accuracy", type: "Metric", value: 99}), (ct:cost{name: "Cost", type: "Metric"}), (ar)-[:CONTAINS {since:2021}]->(eps), (ar)-[:CONTAINS {since:2021}]->(tcs), (ar)-[:CONTAINS {since:2021}]->(aocs), (aocs)-[:HAS {since:2021}]->(strsn), (aocs)-[:HAS {since:2021}]->(li), (tcs)-[:HAS {since:2021}]->(ra), (eps)-[:HAS {since:2021}]->(sa), (li)-[:FUNCTION_OF {since:2021}]->(ac), (strsn)-[:FUNCTION_OF {since:2021}]->(ac), (li)-[:FUNCTION_OF {since:2021}]->(ct), (strsn)-[:FUNCTION_OF {since:2021}]->(ct), (sa)-[:FUNCTION_OF {since:2021}]->(ct), (ra)-[:FUNCTION_OF {since:2021}]->(ct) RETURN ar, eps, aocs, tcs, strsn, li, sa, ra, ac, ct

CREATE (ar:Architecture {name: "ARCH001", type: "Architecture", gdb:"link_to_gdb01.url", liked: "yes", accuracy:99 }), (ar2:Architecture2 {name: "ARCH002", type: "Architecture2", gdb:"link_to_gdb02.url", liked: "no", accuracy:79 }), (ar5:Architecture5 {name: "ARCH005", type: "Architecture5", gdb:"link_to_gdb05.url", liked: "yes", accuracy:90 }) RETURN ar, ar2, ar5

CALL db.schema.visualization()

MATCH (n) DETACH DELETE n
